name = "ming-email-worker"
main = "src/index.ts"
compatibility_date = "2026-05-03"
upload_source_maps = true
workers_dev = false

[[send_email]]
name = "SEND_EMAIL"
remote = true
allowed_sender_addresses = ["noreply@mail.murga.ing"]

[observability]
enabled = true

[vars]
NODE_ENV = "production"
LOG_LEVEL = "info"
