import type { CSSProperties } from "react";

const palette = {
  background: "#000000",
  surface: "#111111",
  surfaceRaised: "#1a1a1a",
  border: "#222222",
  borderVisible: "#333333",
  textDisabled: "#666666",
  textSecondary: "#999999",
  textPrimary: "#e8e8e8",
  textDisplay: "#ffffff",
  accent: "#d71921",
} as const;

export const emailStyles = {
  body: {
    margin: "0",
    backgroundColor: palette.background,
    color: palette.textPrimary,
    fontFamily: "Space Grotesk, DM Sans, Avenir Next, Segoe UI, sans-serif",
  },
  container: {
    width: "100%",
    maxWidth: "560px",
    margin: "0 auto",
    padding: "48px 24px 32px",
  },
  card: {
    border: `1px solid ${palette.borderVisible}`,
    borderRadius: "16px",
    backgroundColor: palette.surface,
    padding: "24px",
  },
  eyebrow: {
    margin: "0 0 48px",
    color: palette.textSecondary,
    fontFamily: "Space Mono, JetBrains Mono, SFMono-Regular, Consolas, monospace",
    fontSize: "11px",
    fontWeight: 400,
    letterSpacing: "0.08em",
    lineHeight: "14px",
    textTransform: "uppercase",
  },
  heading: {
    margin: "0 0 8px",
    color: palette.textDisplay,
    fontSize: "24px",
    fontWeight: 500,
    lineHeight: "29px",
  },
  copy: {
    margin: "0 0 32px",
    color: palette.textSecondary,
    fontSize: "14px",
    lineHeight: "21px",
  },
  codeBox: {
    margin: "0 0 24px",
    border: `1px solid ${palette.borderVisible}`,
    borderRadius: "8px",
    backgroundColor: palette.surfaceRaised,
    padding: "20px 16px",
    textAlign: "center",
  },
  codeLabel: {
    margin: "0 0 12px",
    color: palette.textSecondary,
    fontFamily: "Space Mono, JetBrains Mono, SFMono-Regular, Consolas, monospace",
    fontSize: "11px",
    fontWeight: 400,
    letterSpacing: "0.08em",
    lineHeight: "14px",
    textTransform: "uppercase",
  },
  code: {
    margin: "0",
    color: palette.textDisplay,
    fontFamily: "Space Mono, JetBrains Mono, SFMono-Regular, Consolas, monospace",
    fontSize: "44px",
    fontWeight: 700,
    letterSpacing: "0.16em",
    lineHeight: "48px",
  },
  row: {
    margin: "0",
    borderBottom: `1px solid ${palette.border}`,
    padding: "0 0 12px",
  },
  label: {
    margin: "20px 0 4px",
    color: palette.textSecondary,
    fontFamily: "Space Mono, JetBrains Mono, SFMono-Regular, Consolas, monospace",
    fontSize: "11px",
    fontWeight: 400,
    letterSpacing: "0.08em",
    lineHeight: "14px",
    textTransform: "uppercase",
  },
  value: {
    margin: "0",
    color: palette.textPrimary,
    fontSize: "13px",
    lineHeight: "20px",
    whiteSpace: "pre-wrap",
  },
  accentValue: {
    margin: "0",
    color: palette.accent,
    fontFamily: "Space Mono, JetBrains Mono, SFMono-Regular, Consolas, monospace",
    fontSize: "13px",
    fontWeight: 700,
    letterSpacing: "0.04em",
    lineHeight: "18px",
  },
  divider: {
    margin: "24px 0",
    borderColor: palette.border,
  },
  footer: {
    margin: "20px 0 0",
    color: palette.textDisabled,
    fontFamily: "Space Mono, JetBrains Mono, SFMono-Regular, Consolas, monospace",
    fontSize: "11px",
    letterSpacing: "0.08em",
    lineHeight: "16px",
    textAlign: "center",
    textTransform: "uppercase",
  },
} satisfies Record<string, CSSProperties>;
